# Generated by Django 3.1.1 on 2020-10-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-creation_date',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-creation_date',)},
        ),
    ]
